#ifndef FUNCTYPE_H_
#define FUNCTYPE_H_

// auto generated header file
#define perror_orig_type (void (*)(const char *))
#define strerror_orig_type (char * (*)(int))
#define strerror_r_orig_type (char * (*)(int, char *, size_t))
#define error_orig_type (void (*)(int, int, const char *, ...))
#define exit_orig_type (void (*)(int))
#define mmap_orig_type (void * (*)(void *, size_t, int, int, int, off_t))
#define mmap64_orig_type (void * (*)(void *, size_t, int, int, int, off64_t))
#define accept_orig_type (int (*)(int, struct sockaddr *, socklen_t *))
#define accept4_orig_type (int (*)(int, struct sockaddr *, socklen_t *, int))
#define access_orig_type (int (*)(const char *, int))
#define acct_orig_type (int (*)(const char *))
#define add_key_orig_type (key_serial_t (*)(const char *, const char *, const void *, size_t, key_serial_t))
#define adjtimex_orig_type (int (*)(struct timex *))
#define posix_fadvise_orig_type (int (*)(int, off_t, off_t, int))
#define sync_file_range_orig_type (int (*)(int, off64_t, off64_t, unsigned int))
#define bind_orig_type (int (*)(int, const struct sockaddr *, socklen_t))
#define brk_orig_type (int (*)(void *))
#define sbrk_orig_type (void * (*)(intptr_t))
#define capget_orig_type (int (*)(cap_user_header_t, cap_user_data_t))
#define capset_orig_type (int (*)(cap_user_header_t, const cap_user_data_t))
#define chdir_orig_type (int (*)(const char *))
#define fchdir_orig_type (int (*)(int))
#define chmod_orig_type (int (*)(const char *, mode_t))
#define fchmod_orig_type (int (*)(int, mode_t))
#define chown_orig_type (int (*)(const char *, uid_t, gid_t))
#define fchown_orig_type (int (*)(int, uid_t, gid_t))
#define lchown_orig_type (int (*)(const char *, uid_t, gid_t))
#define chroot_orig_type (int (*)(const char *))
#define clock_getres_orig_type (int (*)(clockid_t, struct timespec *))
#define clock_gettime_orig_type (int (*)(clockid_t, struct timespec *))
#define clock_settime_orig_type (int (*)(clockid_t, const struct timespec *))
#define clock_nanosleep_orig_type (int (*)(clockid_t, int, const struct timespec *, struct timespec *))
#define close_orig_type (int (*)(int))
#define connect_orig_type (int (*)(int, const struct sockaddr *, socklen_t))
#define creat_orig_type (int (*)(const char *, mode_t))
#define dup_orig_type (int (*)(int))
#define dup2_orig_type (int (*)(int, int))
#define dup3_orig_type (int (*)(int, int, int))
#define epoll_create_orig_type (int (*)(int))
#define epoll_create1_orig_type (int (*)(int))
#define epoll_ctl_orig_type (int (*)(int, int, int, struct epoll_event *))
#define epoll_wait_orig_type (int (*)(int, struct epoll_event *, int, int))
#define epoll_pwait_orig_type (int (*)(int, struct epoll_event *, int, int, const sigset_t *))
#define eventfd_orig_type (int (*)(unsigned int, int))
#define faccessat_orig_type (int (*)(int, const char *, int, int))
#define fallocate_orig_type (int (*)(int, int, off_t, off_t))
#define fchmodat_orig_type (int (*)(int, const char *, mode_t, int))
#define fsync_orig_type (int (*)(int))
#define fdatasync_orig_type (int (*)(int))
#define getxattr_orig_type (ssize_t (*)(const char *, const char *, void *, size_t))
#define lgetxattr_orig_type (ssize_t (*)(const char *, const char *, void *, size_t))
#define fgetxattr_orig_type (ssize_t (*)(int, const char *, void *, size_t))
#define flock_orig_type (int (*)(int, int))
#define setxattr_orig_type (int (*)(const char *, const char *, const void *, size_t, int))
#define lsetxattr_orig_type (int (*)(const char *, const char *, const void *, size_t, int))
#define fsetxattr_orig_type (int (*)(int, const char *, const void *, size_t, int))
#define stat_orig_type (int (*)(const char *, struct stat *))
#define fstat_orig_type (int (*)(int, struct stat *))
#define lstat_orig_type (int (*)(const char *, struct stat *))
#define fstatat_orig_type (int (*)(int, const char *, struct stat *, int))
#define statfs_orig_type (int (*)(const char *, struct statfs *))
#define fstatfs_orig_type (int (*)(int, struct statfs *))
#define statvfs_orig_type (int (*)(const char *, struct statvfs *))
#define fstatvfs_orig_type (int (*)(int, struct statvfs *))
#define truncate_orig_type (int (*)(const char *, off_t))
#define ftruncate_orig_type (int (*)(int, off_t))
#define futex_orig_type (int (*)(int *, int, int, const struct timespec *, int *, int))
#define getcwd_orig_type (char * (*)(char *, size_t))
#define getwd_orig_type (char * (*)(char *))
#define get_current_dir_name_orig_type (char * (*)(void))
#define getdomainname_orig_type (int (*)(char *, size_t))
#define setdomainname_orig_type (int (*)(const char *, size_t))
#define getdtablesize_orig_type (int (*)(void))
#define setgroups_orig_type (int (*)(size_t, const gid_t *))
#define gethostid_orig_type (long (*)(void))
#define sethostid_orig_type (int (*)(long))
#define gethostname_orig_type (int (*)(char *, size_t))
#define sethostname_orig_type (int (*)(const char *, size_t))
#define getitimer_orig_type (int (*)(int, struct itimerval *))
#define setitimer_orig_type (int (*)(int, const struct itimerval *, struct itimerval *))
#define get_mempolicy_orig_type (int (*)(int *, unsigned long *, unsigned long, unsigned long, unsigned long))
#define getpagesize_orig_type (int (*)(void))
#define getpeername_orig_type (int (*)(int, struct sockaddr *, socklen_t *))
#define setpgid_orig_type (int (*)(pid_t, pid_t))
#define getpgid_orig_type (pid_t (*)(pid_t))
#define getpriority_orig_type (int (*)(int, int))
#define setpriority_orig_type (int (*)(int, int, int))
#define getresuid_orig_type (int (*)(uid_t *, uid_t *, uid_t *))
#define getresgid_orig_type (int (*)(gid_t *, gid_t *, gid_t *))
#define getrlimit_orig_type (int (*)(int, struct rlimit *))
#define setrlimit_orig_type (int (*)(int, const struct rlimit *))
#define prlimit_orig_type (int (*)(pid_t, int, const struct rlimit *, struct rlimit *))
#define getrusage_orig_type (int (*)(int, struct rusage *))
#define getsid_orig_type (pid_t (*)(pid_t))
#define getsockname_orig_type (int (*)(int, struct sockaddr *, socklen_t *))
#define getsockopt_orig_type (int (*)(int, int, int, void *, socklen_t *))
#define setsockopt_orig_type (int (*)(int, int, int, const void *, socklen_t))
#define gettimeofday_orig_type (int (*)(struct timeval *, struct timezone *))
#define settimeofday_orig_type (int (*)(const struct timeval *, const struct timezone *))
#define inotify_add_watch_orig_type (int (*)(int, const char *, uint32_t))
#define inotify_init_orig_type (int (*)(void))
#define inotify_init1_orig_type (int (*)(int))
#define inotify_rm_watch_orig_type (int (*)(int, int))
#define ioperm_orig_type (int (*)(unsigned long, unsigned long, int))
#define iopl_orig_type (int (*)(int))
#define ipc_orig_type (int (*)(unsigned int, int, int, int, void *, long))
#define kill_orig_type (int (*)(pid_t, int))
#define killpg_orig_type (int (*)(int, int))
#define link_orig_type (int (*)(const char *, const char *))
#define linkat_orig_type (int (*)(int, const char *, int, const char *, int))
#define listen_orig_type (int (*)(int, int))
#define listxattr_orig_type (size_t (*)(const char *, char *, size_t))
#define llistxattr_orig_type (ssize_t (*)(const char *, char *, size_t))
#define flistxattr_orig_type (ssize_t (*)(int, char *, size_t))
#define lookup_dcookie_orig_type (int (*)(u64, char *, size_t))
#define removexattr_orig_type (int (*)(const char *, const char *))
#define lremovexattr_orig_type (int (*)(const char *, const char *))
#define fremovexattr_orig_type (int (*)(int, const char *))
#define lseek_orig_type (off_t (*)(int, off_t, int))
#define madvise_orig_type (int (*)(void *, size_t, int))
#define mbind_orig_type (int (*)(void *, unsigned long, int, unsigned long *, unsigned long, unsigned))
#define migrate_pages_orig_type (long (*)(int, unsigned long, const unsigned long *, const unsigned long *))
#define mincore_orig_type (int (*)(void *, size_t, unsigned char *))
#define mkdir_orig_type (int (*)(const char *, mode_t))
#define mkdirat_orig_type (int (*)(int, const char *, mode_t))
#define mknod_orig_type (int (*)(const char *, mode_t, dev_t))
#define mknodat_orig_type (int (*)(int, const char *, mode_t, dev_t))
#define mlock_orig_type (int (*)(const void *, size_t))
#define munlock_orig_type (int (*)(const void *, size_t))
#define mlockall_orig_type (int (*)(int))
#define munlockall_orig_type (int (*)(void))
#define munmap_orig_type (int (*)(void *, size_t))
#define mmap2_orig_type (void * (*)(void *, size_t, int, int, int, off_t))
#define mount_orig_type (int (*)(const char *, const char *, const char *, unsigned long, const void *))
#define mprotect_orig_type (int (*)(void *, size_t, int))
#define mq_notify_orig_type (int (*)(mqd_t, const struct sigevent *))
#define mq_receive_orig_type (ssize_t (*)(mqd_t, char *, size_t, unsigned *))
#define mq_timedreceive_orig_type (ssize_t (*)(mqd_t, char *, size_t, unsigned *, const struct timespec *))
#define mq_send_orig_type (int (*)(mqd_t, const char *, size_t, unsigned))
#define mq_timedsend_orig_type (int (*)(mqd_t, const char *, size_t, unsigned, const struct timespec *))
#define mq_unlink_orig_type (int (*)(const char *))
#define msgctl_orig_type (int (*)(int, int, struct msqid_ds *))
#define msgget_orig_type (int (*)(key_t, int))
#define msgsnd_orig_type (int (*)(int, const void *, size_t, int))
#define msgrcv_orig_type (ssize_t (*)(int, void *, size_t, long, int))
#define msync_orig_type (int (*)(void *, size_t, int))
#define nanosleep_orig_type (int (*)(const struct timespec *, struct timespec *))
#define select_orig_type (int (*)(int, fd_set *, fd_set *, fd_set *, struct timeval *))
#define pselect_orig_type (int (*)(int, fd_set *, fd_set *, fd_set *, const struct timespec *, const sigset_t *))
#define nfsservctl_orig_type (long (*)(int, struct nfsctl_arg *, union nfsctl_res *))
#define nice_orig_type (int (*)(int))
#define uname_orig_type (int (*)(struct utsname *))
#define pause_orig_type (int (*)(void))
#define pciconfig_read_orig_type (int (*)(unsigned long, unsigned long, unsigned long, unsigned long, void *))
#define pciconfig_write_orig_type (int (*)(unsigned long, unsigned long, unsigned long, unsigned long, void *))
#define pciconfig_iobase_orig_type (int (*)(long, unsigned long, unsigned long))
#define personality_orig_type (int (*)(unsigned long))
#define poll_orig_type (int (*)(struct pollfd *, nfds_t, int))
#define ppoll_orig_type (int (*)(struct pollfd *, nfds_t, const struct timespec *, const sigset_t *))
#define prctl_orig_type (int (*)(int, unsigned long, unsigned long, unsigned long, unsigned long))
#define pread_orig_type (ssize_t (*)(int, void *, size_t, off_t))
#define pwrite_orig_type (ssize_t (*)(int, const void *, size_t, off_t))
#define readv_orig_type (ssize_t (*)(int, const struct iovec *, int))
#define writev_orig_type (ssize_t (*)(int, const struct iovec *, int))
#define preadv_orig_type (ssize_t (*)(int, const struct iovec *, int, off_t))
#define pwritev_orig_type (ssize_t (*)(int, const struct iovec *, int, off_t))
#define process_vm_readv_orig_type (ssize_t (*)(pid_t, const struct iovec *, unsigned long, const struct iovec *, unsigned long, unsigned long))
#define process_vm_writev_orig_type (ssize_t (*)(pid_t, const struct iovec *, unsigned long, const struct iovec *, unsigned long, unsigned long))
#define ptrace_orig_type (long (*)(enum __ptrace_request, pid_t, void *, void *))
#define quotactl_orig_type (int (*)(int, const char *, int, caddr_t))
#define read_orig_type (ssize_t (*)(int, void *, size_t))
#define readahead_orig_type (ssize_t (*)(int, off64_t, size_t))
#define readlink_orig_type (ssize_t (*)(const char *, char *, size_t))
#define readlinkat_orig_type (int (*)(int, const char *, char *, size_t))
#define reboot_orig_type (int (*)(int))
#define recv_orig_type (ssize_t (*)(int, void *, size_t, int))
#define recvfrom_orig_type (ssize_t (*)(int, void *, size_t, int, struct sockaddr *, socklen_t *))
#define recvmsg_orig_type (ssize_t (*)(int, struct msghdr *, int))
#define recvmmsg_orig_type (int (*)(int, struct mmsghdr *, unsigned int, unsigned int, struct timespec *))
#define remap_file_pages_orig_type (int (*)(void *, size_t, int, ssize_t, int))
#define rename_orig_type (int (*)(const char *, const char *))
#define renameat_orig_type (int (*)(int, const char *, int, const char *))
#define request_key_orig_type (key_serial_t (*)(const char *, const char *, const char *, key_serial_t))
#define rmdir_orig_type (int (*)(const char *))
#define sigaction_orig_type (int (*)(int, const struct sigaction *, struct sigaction *))
#define sigpending_orig_type (int (*)(sigset_t *))
#define sigprocmask_orig_type (int (*)(int, const sigset_t *, sigset_t *))
#define sigsuspend_orig_type (int (*)(const sigset_t *))
#define sigwaitinfo_orig_type (int (*)(const sigset_t *, siginfo_t *))
#define sigtimedwait_orig_type (int (*)(const sigset_t *, siginfo_t *, const struct timespec *))
#define sched_setaffinity_orig_type (int (*)(pid_t, size_t, cpu_set_t *))
#define sched_getaffinity_orig_type (int (*)(pid_t, size_t, cpu_set_t *))
#define sched_setparam_orig_type (int (*)(pid_t, const struct sched_param *))
#define sched_getparam_orig_type (int (*)(pid_t, struct sched_param *))
#define sched_get_priority_max_orig_type (int (*)(int))
#define sched_get_priority_min_orig_type (int (*)(int))
#define sched_setscheduler_orig_type (int (*)(pid_t, int, const struct sched_param *))
#define sched_getscheduler_orig_type (int (*)(pid_t))

#endif /* FUNCTYPE_H_ */
