#ifndef FUNCTYPE_H_
#define FUNCTYPE_H_

// auto generated header file
#define perror_orig_type (void (*)(const char *))
#define strerror_orig_type (char * (*)(int))
#define strerror_r_orig_type (char * (*)(int, char *, size_t))
#define error_orig_type (void (*)(int, int, const char *, ...))
#define mmap_orig_type (void * (*)(void *, size_t, int, int, int, off_t))
#define mmap64_orig_type (void * (*)(void *, size_t, int, int, int, off64_t))
#define accept_orig_type (int (*)(int, struct sockaddr *, socklen_t *))
#define accept4_orig_type (int (*)(int, struct sockaddr *, socklen_t *, int))
#define access_orig_type (int (*)(const char *, int))
#define acct_orig_type (int (*)(const char *))
#define add_key_orig_type (key_serial_t (*)(const char *, const char *, const void *, size_t, key_serial_t))
#define adjtimex_orig_type (int (*)(struct timex *))
#define posix_fadvise_orig_type (int (*)(int, off_t, off_t, int))
#define sync_file_range_orig_type (int (*)(int, off64_t, off64_t, unsigned int))
#define bind_orig_type (int (*)(int, const struct sockaddr *, socklen_t))
#define brk_orig_type (int (*)(void *))
#define sbrk_orig_type (void * (*)(intptr_t))
#define cacheflush_orig_type (int (*)(char *, int, int))
#define capget_orig_type (int (*)(cap_user_header_t, cap_user_data_t))
#define capset_orig_type (int (*)(cap_user_header_t, const cap_user_data_t))
#define chdir_orig_type (int (*)(const char *))
#define fchdir_orig_type (int (*)(int))
#define chmod_orig_type (int (*)(const char *, mode_t))
#define fchmod_orig_type (int (*)(int, mode_t))
#define chown_orig_type (int (*)(const char *, uid_t, gid_t))
#define fchown_orig_type (int (*)(int, uid_t, gid_t))
#define lchown_orig_type (int (*)(const char *, uid_t, gid_t))
#define chroot_orig_type (int (*)(const char *))
#define clock_getres_orig_type (int (*)(clockid_t, struct timespec *))
#define clock_gettime_orig_type (int (*)(clockid_t, struct timespec *))
#define clock_settime_orig_type (int (*)(clockid_t, const struct timespec *))
#define clock_nanosleep_orig_type (int (*)(clockid_t, int, const struct timespec *, struct timespec *))
#define close_orig_type (int (*)(int))
#define connect_orig_type (int (*)(int, const struct sockaddr *, socklen_t))
#define creat_orig_type (int (*)(const char *, mode_t))
#define dup_orig_type (int (*)(int))
#define dup2_orig_type (int (*)(int, int))
#define dup3_orig_type (int (*)(int, int, int))
#define epoll_create_orig_type (int (*)(int))
#define epoll_create1_orig_type (int (*)(int))
#define epoll_ctl_orig_type (int (*)(int, int, int, struct epoll_event *))
#define epoll_wait_orig_type (int (*)(int, struct epoll_event *, int, int))
#define epoll_pwait_orig_type (int (*)(int, struct epoll_event *, int, int, const sigset_t *))
#define eventfd_orig_type (int (*)(unsigned int, int))
#define exit_orig_type (void (*)(int))
#define faccessat_orig_type (int (*)(int, const char *, int, int))
#define fallocate_orig_type (int (*)(int, int, off_t, off_t))
#define fchmodat_orig_type (int (*)(int, const char *, mode_t, int))
#define fsync_orig_type (int (*)(int))
#define fdatasync_orig_type (int (*)(int))
#define getxattr_orig_type (ssize_t (*)(const char *, const char *, void *, size_t))
#define lgetxattr_orig_type (ssize_t (*)(const char *, const char *, void *, size_t))
#define fgetxattr_orig_type (ssize_t (*)(int, const char *, void *, size_t))
#define stat_orig_type (int (*)(const char *, struct stat *))
#define fstat_orig_type (int (*)(int, struct stat *))
#define lstat_orig_type (int (*)(const char *, struct stat *))
#define fstatat_orig_type (int (*)(int, const char *, struct stat *, int))
#define statfs_orig_type (int (*)(const char *, struct statfs *))
#define fstatfs_orig_type (int (*)(int, struct statfs *))
#define statvfs_orig_type (int (*)(const char *, struct statvfs *))
#define fstatvfs_orig_type (int (*)(int, struct statvfs *))
#define truncate_orig_type (int (*)(const char *, off_t))
#define ftruncate_orig_type (int (*)(int, off_t))
#define futex_orig_type (int (*)(int *, int, int, const struct timespec *, int *, int))
#define getcwd_orig_type (char * (*)(char *, size_t))
#define getwd_orig_type (char * (*)(char *))
#define get_current_dir_name_orig_type (char * (*)(void))
#define getdomainname_orig_type (int (*)(char *, size_t))
#define setdomainname_orig_type (int (*)(const char *, size_t))
#define getdtablesize_orig_type (int (*)(void))
#define setgroups_orig_type (int (*)(size_t, const gid_t *))
#define gethostid_orig_type (long (*)(void))
#define sethostid_orig_type (int (*)(long))
#define gethostname_orig_type (int (*)(char *, size_t))
#define sethostname_orig_type (int (*)(const char *, size_t))
#define getitimer_orig_type (int (*)(int, struct itimerval *))
#define setitimer_orig_type (int (*)(int, const struct itimerval *, struct itimerval *))
#define get_mempolicy_orig_type (int (*)(int *, unsigned long *, unsigned long, unsigned long, unsigned long))
#define getpagesize_orig_type (int (*)(void))
#define getpeername_orig_type (int (*)(int, struct sockaddr *, socklen_t *))
#define setpgid_orig_type (int (*)(pid_t, pid_t))
#define getpgid_orig_type (pid_t (*)(pid_t))
#define getpriority_orig_type (int (*)(int, int))
#define setpriority_orig_type (int (*)(int, int, int))
#define getresuid_orig_type (int (*)(uid_t *, uid_t *, uid_t *))
#define getresgid_orig_type (int (*)(gid_t *, gid_t *, gid_t *))
#define getrlimit_orig_type (int (*)(int, struct rlimit *))
#define setrlimit_orig_type (int (*)(int, const struct rlimit *))
#define prlimit_orig_type (int (*)(pid_t, int, const struct rlimit *, struct rlimit *))
#define getrusage_orig_type (int (*)(int, struct rusage *))
#define getsid_orig_type (pid_t (*)(pid_t))
#define getsockname_orig_type (int (*)(int, struct sockaddr *, socklen_t *))
#define getsockopt_orig_type (int (*)(int, int, int, void *, socklen_t *))
#define setsockopt_orig_type (int (*)(int, int, int, const void *, socklen_t))
#define gettimeofday_orig_type (int (*)(struct timeval *, struct timezone *))
#define settimeofday_orig_type (int (*)(const struct timeval *, const struct timezone *))
#define inb_orig_type (unsigned char (*)(unsigned short int))
#define inb_p_orig_type (unsigned char (*)(unsigned short int))
#define inw_orig_type (unsigned short int (*)(unsigned short int))
#define inw_p_orig_type (unsigned short int (*)(unsigned short int))
#define inl_orig_type (unsigned int (*)(unsigned short int))
#define inl_p_orig_type (unsigned int (*)(unsigned short int))
#define outb_orig_type (void (*)(unsigned char, unsigned short int))
#define outb_p_orig_type (void (*)(unsigned char, unsigned short int))
#define outw_orig_type (void (*)(unsigned short int, unsigned short int))
#define outw_p_orig_type (void (*)(unsigned short int, unsigned short int))
#define outl_orig_type (void (*)(unsigned int, unsigned short int))
#define outl_p_orig_type (void (*)(unsigned int, unsigned short int))
#define insb_orig_type (void (*)(unsigned short int, void *, unsigned long int))
#define insw_orig_type (void (*)(unsigned short int, void *, unsigned long int))
#define insl_orig_type (void (*)(unsigned short int, void *, unsigned long int))
#define outsb_orig_type (void (*)(unsigned short int, const void *, unsigned long int))
#define outsw_orig_type (void (*)(unsigned short int, const void *, unsigned long int))
#define outsl_orig_type (void (*)(unsigned short int, const void *, unsigned long int))
#define inotify_add_watch_orig_type (int (*)(int, const char *, uint32_t))
#define inotify_init_orig_type (int (*)(void))
#define inotify_init1_orig_type (int (*)(int))
#define inotify_rm_watch_orig_type (int (*)(int, int))

#endif /* FUNCTYPE_H_ */
